apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: Secure Supply Chain Example for Spring Boot® using Maven
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain
      icon: dashboard
      type: admin-dashboard
  tags:
    - java
    - spring
    - ssc
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
