apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.name  }}
  namespace: rhtap 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: components/overlays/development
    repoURL: ${{ values.repoUrl }}
    targetRevision: main
  destination:
    namespace: ${{ values.namespace }} 
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
